### PR TITLE
Add login with Azure AD app certificate and Sites.Selected

### PR DESCRIPTION
**Pull request by rikroe**
This PR adds an additional preset and login mechanism: Azure AD app registrations with certificate authentication.

If there are any change requests in terms of wording for this PR or suggestions how to better deal with the private key in the parameters (especially regarding spaces/newlines), happy to incorporate them. The `client_secret` can unfortunately not be used.

I've added the `msal` library to do the authentication, but it could be done manually using `PyJWT[crypto]` and `cryptography`.

### Reason
Microsoft is by default deactivating the ability to add new Site App registrations or change those permissions by **mid of September** (see [MC660075](https://m365admin.handsontek.net/sharepoint-admin-control-for-app-registration-update/)).
While it can be turned on again, our Sharepoint Admins won't do this.

To access specific sites only, one can create an App Registration in Azure AD and grant the **Sharepoint** `Sites.Selected` permission. While this was orignally only available to Graph APIs, it is now possible to use these permissions with the original Sharepoint REST API (as used by this plugin) as well.
More information and how to grant permission can be found in the [announcement blog post](https://devblogs.microsoft.com/microsoft365dev/updates-on-controlling-app-specific-access-on-specific-sharepoint-sites-sites-selected/) and this [detailled blog post](https://techcommunity.microsoft.com/t5/microsoft-sharepoint-blog/develop-applications-that-use-sites-selected-permissions-for-spo/ba-p/3790476).

### CODE REVIEW

**Comment by pkbullock** [comment]
Hi @alexbourret - I have interest in this option too, is there any movement on this feature? Currently, the plugin isnt using the most secure methods of connecting to the product.

**Comment by alexbourret** [comment]
Hi @pkbullock - We just got the new sharepoint QA instance to test this feature, so it is next on the list
@rikroe - Thank you for the PR ! No need to rebase, I can do it since we have to add a few things (tests, support for keys containing "encrypted" in the header...)

**Comment by pkbullock** [comment]
Thank you @alexbourret - do you have a ball park timeline for this?

**Comment by alexbourret** [comment]
@pkbullock - the feature is now released in v1.1.3. 
@rikroe - Thank you again for your contribution ! I'm closing this PR but your code is now included and I've added your name to the [contributors file](https://github.com/dataiku/dss-plugin-sharepoint-online/blob/master/CONTRIBUTORS).

**Comment by alexbourret** [comment]
Feature merged with [PR #50](https://github.com/dataiku/dss-plugin-sharepoint-online/pull/50)

**Pull request closed without merging**
